version: "3.9"
services:
  good_night_mysql:
    container_name: good_night_mysql
    image: mysql:8.0.31
    volumes:
      - db:/var/lib/mysql
      - ./docker-compose-db-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: gnpassword
      MYSQL_USER: gn_user
      MYSQL_PASSWORD: gn_user
    networks:
      - good_night_net
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.0
    restart: always
    volumes:
      - zookeeper-volume:/var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - kafka-volume:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

volumes:
  db:
    name: good_night_db
  zookeeper-volume:
    name: zookeeper-volume
  kafka-volume:
    name: kafka-volume

networks:
  good_night_net:
    name: good_night_net
