version: "3.9"
services:
  good_night_mysql:
    container_name: good_night_mysql
    image: mysql:8.0.31
    volumes:
      - db:/var/lib/mysql
      - ./docker-compose-db-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_POOL: ${MYSQL_POOL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    networks:
      - good_night_net
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.0
    restart: always
    volumes:
      - zookeeper-volume:/var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    networks:
      - good_night_net

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - kafka-volume:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
    networks:
      - good_night_net


  good_night_api:
    build:
      context: ../
      dockerfile: deploy/api/Dockerfile
    depends_on:
      - good_night_mysql
      - kafka
    ports:
      - "3000:3000"
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_POOL: ${MYSQL_POOL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - good_night_net

  schedule_clock_in_consumer:
    build:
      context: ../
      dockerfile: deploy/schedule_clock_in_consumer/Dockerfile
    depends_on:
      - good_night_mysql
      - kafka
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_POOL: ${MYSQL_POOL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    restart: on-failure
    networks:
      - good_night_net

volumes:
  db:
    name: good_night_db
  zookeeper-volume:
    name: zookeeper-volume
  kafka-volume:
    name: kafka-volume

networks:
  good_night_net:
    name: good_night_net
